name: Upload to SourceForge

on:
  workflow_dispatch:
    inputs:
        DL_LINK:
          description: "Link of the File to Upload:"
          required: true
        
        DEVICE_CODENAME:
          description: "Device Codename:"
          required: true

defaults:
  run:
    shell: bash

env:
  DEVICE: ${{ github.event.inputs.DEVICE_CODENAME }}
  ROM: ${{ github.event.inputs.ROM_NAME }}
  DOWNLOAD_LINK: ${{ github.event.inputs.DL_LINK }}

  # SourceForge Credentials
  SF_USERNAME: ${{ secrets.SF_USERNAME }}
  SF_PASS: ${{ secrets.SF_PASSWORD }}
  SF_PROJECT: orangefoxrecovery

  # Temp (Download) Directory
  TMP_DIR: /tmp/fox

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkouts
        uses: actions/checkout@v2

      - name: Download Build
        run: |
          bash download.sh

      - name: Upload the Build
        run: |
          export SF_UPLOAD_DIR=$DEVICE

          sshpass -p ${SF_PASS} rsync -aPe "ssh -o StrictHostKeyChecking=no" ${TMP_DIR}/* --progress -r ${SF_USERNAME}@frs.sourceforge.net:/home/frs/project/${SF_PROJECT}/${SF_UPLOAD_DIR}/
